version: 1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
    working_directory: ~/[your_app  ]
    branches:
      only:
        - master

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - ""
      - run: sudo apt-get update && sudo apt-get install rsync
      - run: cd ~/[your_app]/scripts && ./build-theme.sh
      - deploy:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              rsync -e "ssh -o StrictHostKeyChecking=no" --exclude \*node_modules\* -avc ~/[your_app]/wp-content/themes/steen root@[your_app].steenify.com:/var/www/html/wp-content/themes
            else
              echo "Not master branch..."
            fi                
      # end